'use client'

import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, Compass, MapPin, Menu, Mountain, Phone, ShieldCheck, Sparkles, Trees, Truck, Users, X } from 'lucide-react'

const phone = '919876543210'
const routes = [
  { no: '01', title: 'Peak & Mist Trail', tag: 'Most Popular', image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=85', places: ['Mullayanagiri', 'Jhari Waterfalls', 'Honnammana Falls', 'Baba Budangiri'] },
  { no: '02', title: 'Waterfall & Valley Explorer', tag: 'Scenic & Adventure', image: 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=1200&q=85', places: ['Deviramma Temple', 'Kemmanagundi', 'Kallathigiri Falls', 'Hebbe Waterfalls'] },
  { no: '03', title: 'Wild Safari & Plantations', tag: 'Nature & Wildlife', image: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1200&q=85', places: ['Malandaru Shooting Point', 'Muthodi Forest', 'Bhadra Wildlife Sanctuary', 'Lush Coffee Estates'] },
  { no: '04', title: 'Heritage & Watersports', tag: 'Spiritual & Historical', image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=85', places: ['Belur Temple', 'Halebidu Temple', 'Yagachi Water Sports'] },
]
const wa = (message: string) => `https://wa.me/${phone}?text=${encodeURIComponent(message)}`

export default function Home() {
  const [open, setOpen] = useState(false)
  const [route, setRoute] = useState('Peak & Mist Trail')
  const [sent, setSent] = useState(false)
  const book = (selected: string) => { setRoute(selected); document.getElementById('booking')?.scrollIntoView({ behavior: 'smooth' }) }
  return <>
    <header className="nav"><a href="#top" className="brand"><span className="brand-mark"><Mountain size={21}/></span><span>Chikmagalur <b>Travel</b></span></a><nav className={open ? 'show' : ''}>{[['Routes','routes'],['Experience','experience'],['Why Choose Us','why'],['Contact','booking']].map(([name,id]) => <a onClick={() => setOpen(false)} href={`#${id}`} key={id}>{name}</a>)}</nav><a href="#booking" className="nav-cta">Book a Jeep <ArrowRight size={16}/></a><button aria-label="Toggle menu" className="menu" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></header>
    <main id="top">
      <section className="hero"><div className="hero-art"/><div className="hero-content"><div className="eyebrow"><Compass size={15}/> Off-Road Jeep Expeditions</div><p className="kicker">Chikmagalur, Karnataka</p><h1>Leave the road.<br/><em>Take the trails.</em></h1><p className="hero-copy">Explore the hidden gems of Chikmagalur on specially curated off-road jeep routes — from mist-covered peaks and waterfalls to dense forests and historic temples.</p><div className="hero-actions"><a className="button primary" href="#routes">Explore routes <ArrowRight size={18}/></a><a className="button ghost" href={wa('Hello! I would like to enquire about a Chikmagalur jeep tour.')} target="_blank">Instant WhatsApp <ArrowRight size={18}/></a></div><div className="trust"><span><ShieldCheck/> Verified local drivers</span><span><Truck/> Safe 4x4 jeeps</span><span><Sparkles/> Custom timings</span></div></div><div className="trail-card"><span className="trail-icon"><Trees size={21}/></span><div><p>Today&apos;s trail mood</p><strong>Mist · Forest · Open skies</strong></div><span className="trail-line"/></div><a href="#routes" className="scroll">Scroll to explore <ChevronDown size={17}/></a></section>
      <section id="experience" className="intro section"><div><p className="overline">Beyond the usual</p><h2>A better way to see<br/>the <em>Malnad</em>.</h2></div><p>Every route is an invitation to get a little closer to the wild. Our local drivers know where the clouds linger, when the falls are at their best, and the tracks that turn a day trip into a story.</p><div className="intro-stat"><strong>4</strong><span>signature<br/>routes</span></div></section>
      <section id="routes" className="routes section"><div className="section-head"><div><p className="overline">Choose your trail</p><h2>Curated <em>jeep journeys.</em></h2></div><p>Private, unhurried and always per jeep.<br/>Pick a route or let us shape one for you.</p></div><div className="route-grid">{routes.map((item, i) => <article className={`route-card route-${i}`} key={item.title}><div className="route-image" style={{backgroundImage:`linear-gradient(180deg, transparent 30%, rgba(3,11,8,.93)), url(${item.image})`}}><div className="route-top"><span>{item.no}</span><span className="tag">{item.tag}</span></div><span className="image-label"><MapPin size={13}/> Chikmagalur</span></div><div className="route-body"><div className="route-meta"><p className="per-jeep">Private tour</p><span>Per Jeep</span></div><h3>{item.title}</h3><ul>{item.places.map(place => <li key={place}><Check size={15}/>{place}</li>)}</ul><button onClick={() => book(item.title)}>Book this route <ArrowRight size={17}/></button></div></article>)}</div></section>
      <section id="why" className="why section"><div className="why-lead"><p className="overline">The Chikmagalur Travel way</p><h2>Made for the<br/><em>road less travelled.</em></h2><p>Comfort, confidence and the kind of local knowledge that only comes from a lifetime in these hills.</p><a href="#booking" className="text-link">Plan your escape <ArrowRight size={17}/></a></div><div className="benefits">{[[Users,'Experienced mountain drivers','Local experts who know every bend, viewpoint and hidden turn.'],[Truck,'Well-maintained 4x4 jeeps','Rugged, comfortable and ready for the terrain.'],[MapPin,'Flexible pickup & drop','We meet you where it works best — stay, station or town.'],[Compass,'Custom itineraries','Your pace, your people, your perfect mountain day.']].map(([Icon,title,text]) => { const I = Icon as typeof Users; return <div className="benefit" key={title as string}><span><I size={23}/></span><h3>{title as string}</h3><p>{text as string}</p></div>})}</div></section>
      <section id="booking" className="booking"><div className="booking-inner"><div className="booking-copy"><p className="overline">Start your journey</p><h2>Ready for an adventure<br/><em>of a lifetime?</em></h2><p>Tell us where you want to go. We will take care of the trail.</p><div className="contact-buttons"><a href="tel:+919876543210"><Phone size={18}/> Direct call</a><a className="whatsapp" target="_blank" href={wa('Hello! I would like to book a Chikmagalur jeep expedition.')}><span>◉</span> WhatsApp us</a></div></div><form onSubmit={(e) => { e.preventDefault(); setSent(true) }}><label>Your name<input required placeholder="Your full name"/></label><label>Phone number<input required type="tel" placeholder="Your phone number"/></label><div className="form-row"><label>Selected route<select value={route} onChange={(e) => setRoute(e.target.value)}>{routes.map(r => <option key={r.title}>{r.title}</option>)}<option>Custom route</option></select></label><label>Preferred date<input required type="date"/></label></div><button className="form-submit" type="submit">{sent ? 'Enquiry received — thank you!' : 'Send enquiry'} <ArrowRight size={18}/></button>{sent && <p className="form-note">We’ll get back to you shortly to confirm your adventure.</p>}</form></div></section>
    </main><footer><a className="brand" href="#top"><span className="brand-mark"><Mountain size={18}/></span>Chikmagalur <b>Travel</b></a><p>© 2026 Chikmagalur Travel. Demo website.</p><p>Routes are weather and access dependent.</p></footer>
  </>
}
